//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixteenCoreCharacterMapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixteenCoreCharacterMapper.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how prone one is to worry and self-doubt.
        /// </summary>
        public static string Trait_Anxiety_Description {
            get {
                return ResourceManager.GetString("Trait_Anxiety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worried, self-doubting, apprehensive, insecure, easily hurt, prone to guilt, dwells on past mistakes.
        /// </summary>
        public static string Trait_Anxiety_High {
            get {
                return ResourceManager.GetString("Trait_Anxiety_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-assured, confident, unworried, secure, not easily bothered, resilient to discouragement, free of guilt.
        /// </summary>
        public static string Trait_Anxiety_Low {
            get {
                return ResourceManager.GetString("Trait_Anxiety_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety.
        /// </summary>
        public static string Trait_Anxiety_Name {
            get {
                return ResourceManager.GetString("Trait_Anxiety_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how assertive one is with others.
        /// </summary>
        public static string Trait_Assertiveness_Description {
            get {
                return ResourceManager.GetString("Trait_Assertiveness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assertive, takes charge, says what they think, directs others, takes control of situations, unafraid of criticism.
        /// </summary>
        public static string Trait_Assertiveness_High {
            get {
                return ResourceManager.GetString("Trait_Assertiveness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accommodating, conflict-averse, lets others lead, avoids challenges, can be pushed around, defers to others.
        /// </summary>
        public static string Trait_Assertiveness_Low {
            get {
                return ResourceManager.GetString("Trait_Assertiveness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertiveness.
        /// </summary>
        public static string Trait_Assertiveness_Name {
            get {
                return ResourceManager.GetString("Trait_Assertiveness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how receptive to new ideas and experiences one is.
        /// </summary>
        public static string Trait_Complexity_Description {
            get {
                return ResourceManager.GetString("Trait_Complexity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experimental, open to new ideas, prefers variety, enjoys complexity and theoretical discussions, thinks up new ways of doing things.
        /// </summary>
        public static string Trait_Complexity_High {
            get {
                return ResourceManager.GetString("Trait_Complexity_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traditional, conventional, prefers the familiar and routine, avoids abstract or philosophical discussions.
        /// </summary>
        public static string Trait_Complexity_Low {
            get {
                return ResourceManager.GetString("Trait_Complexity_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        public static string Trait_Complexity_Name {
            get {
                return ResourceManager.GetString("Trait_Complexity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how suspicious one is of others.
        /// </summary>
        public static string Trait_Distrust_Description {
            get {
                return ResourceManager.GetString("Trait_Distrust_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suspicious, vigilant, skeptical, wary of others, suspects hidden motives, finds it hard to forgive, distrustful.
        /// </summary>
        public static string Trait_Distrust_High {
            get {
                return ResourceManager.GetString("Trait_Distrust_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trusting, accepting, believes what people say, assumes good intentions, sees people as basically moral.
        /// </summary>
        public static string Trait_Distrust_Low {
            get {
                return ResourceManager.GetString("Trait_Distrust_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrust.
        /// </summary>
        public static string Trait_Distrust_Name {
            get {
                return ResourceManager.GetString("Trait_Distrust_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how much one abides by rules and duties.
        /// </summary>
        public static string Trait_Dutifulness_Description {
            get {
                return ResourceManager.GetString("Trait_Dutifulness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dutiful, rule-conscious, respects authority, follows rules, believes in order and enforcement, conventional.
        /// </summary>
        public static string Trait_Dutifulness_High {
            get {
                return ResourceManager.GetString("Trait_Dutifulness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-conforming, expedient, resists authority, breaks rules, values personal freedom over convention.
        /// </summary>
        public static string Trait_Dutifulness_Low {
            get {
                return ResourceManager.GetString("Trait_Dutifulness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutifulness.
        /// </summary>
        public static string Trait_Dutifulness_Name {
            get {
                return ResourceManager.GetString("Trait_Dutifulness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how easily frustrated or irritated one is.
        /// </summary>
        public static string Trait_Emotionality_Description {
            get {
                return ResourceManager.GetString("Trait_Emotionality_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tense, impatient, easily irritated, quick to anger, frustrated, annoyed by others&apos; mistakes, easily put out.
        /// </summary>
        public static string Trait_Emotionality_High {
            get {
                return ResourceManager.GetString("Trait_Emotionality_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relaxed, placid, patient, calm, not easily annoyed, quick to forgive, tranquil, composed.
        /// </summary>
        public static string Trait_Emotionality_Low {
            get {
                return ResourceManager.GetString("Trait_Emotionality_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotionality.
        /// </summary>
        public static string Trait_Emotionality_Name {
            get {
                return ResourceManager.GetString("Trait_Emotionality_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how composed one is under pressure.
        /// </summary>
        public static string Trait_EmotionalStability_Description {
            get {
                return ResourceManager.GetString("Trait_EmotionalStability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resilient, emotionally stable, relaxed, calm under pressure, readily overcomes setbacks, comfortable with oneself.
        /// </summary>
        public static string Trait_EmotionalStability_High {
            get {
                return ResourceManager.GetString("Trait_EmotionalStability_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reactive, emotionally changeable, easily discouraged, prone to feeling blue, dislikes oneself, feels desperate under stress.
        /// </summary>
        public static string Trait_EmotionalStability_Low {
            get {
                return ResourceManager.GetString("Trait_EmotionalStability_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional Stability.
        /// </summary>
        public static string Trait_EmotionalStability_Name {
            get {
                return ResourceManager.GetString("Trait_EmotionalStability_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how expressive and energetic one is.
        /// </summary>
        public static string Trait_Gregariousness_Description {
            get {
                return ResourceManager.GetString("Trait_Gregariousness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lively, energetic, spontaneous, expressive, loves parties and crowds, jokes around, can be wild and crazy.
        /// </summary>
        public static string Trait_Gregariousness_High {
            get {
                return ResourceManager.GetString("Trait_Gregariousness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serious, restrained, introspective, quiet, dislikes crowds and loud events, sober in demeanor.
        /// </summary>
        public static string Trait_Gregariousness_Low {
            get {
                return ResourceManager.GetString("Trait_Gregariousness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gregariousness.
        /// </summary>
        public static string Trait_Gregariousness_Name {
            get {
                return ResourceManager.GetString("Trait_Gregariousness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how imaginative and abstract one is.
        /// </summary>
        public static string Trait_Imagination_Description {
            get {
                return ResourceManager.GetString("Trait_Imagination_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imaginative, abstract, absorbed in ideas, loves to daydream and fantasize, can be unconventional or strange.
        /// </summary>
        public static string Trait_Imagination_High {
            get {
                return ResourceManager.GetString("Trait_Imagination_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grounded, practical, conventional, solution-oriented, does things by the book, seldom daydreams.
        /// </summary>
        public static string Trait_Imagination_Low {
            get {
                return ResourceManager.GetString("Trait_Imagination_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagination.
        /// </summary>
        public static string Trait_Imagination_Name {
            get {
                return ResourceManager.GetString("Trait_Imagination_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how analytical one&apos;s thinking is.
        /// </summary>
        public static string Trait_Intellect_Description {
            get {
                return ResourceManager.GetString("Trait_Intellect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analytical, insightful, quick to learn, enjoys abstract ideas and complex arguments, reflects before acting.
        /// </summary>
        public static string Trait_Intellect_High {
            get {
                return ResourceManager.GetString("Trait_Intellect_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concrete, straightforward, avoids complexity, gets confused by abstract ideas, has a simple vocabulary.
        /// </summary>
        public static string Trait_Intellect_Low {
            get {
                return ResourceManager.GetString("Trait_Intellect_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect.
        /// </summary>
        public static string Trait_Intellect_Name {
            get {
                return ResourceManager.GetString("Trait_Intellect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how self-reliant and solitary one is.
        /// </summary>
        public static string Trait_Introversion_Description {
            get {
                return ResourceManager.GetString("Trait_Introversion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-reliant, solitary, individualistic, enjoys privacy and quiet, prefers to be alone, self-sufficient.
        /// </summary>
        public static string Trait_Introversion_High {
            get {
                return ResourceManager.GetString("Trait_Introversion_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group-oriented, affiliative, enjoys teamwork, needs the company of others, collaborative, a joiner.
        /// </summary>
        public static string Trait_Introversion_Low {
            get {
                return ResourceManager.GetString("Trait_Introversion_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introversion.
        /// </summary>
        public static string Trait_Introversion_Name {
            get {
                return ResourceManager.GetString("Trait_Introversion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how organized and disciplined one is.
        /// </summary>
        public static string Trait_Orderliness_Description {
            get {
                return ResourceManager.GetString("Trait_Orderliness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfectionistic, organized, self-disciplined, exacting, likes order, wants things &apos;just right&apos;, finishes tasks right away.
        /// </summary>
        public static string Trait_Orderliness_High {
            get {
                return ResourceManager.GetString("Trait_Orderliness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flexible, tolerates disorder, unexacting, lax, spontaneous, not bothered by mess, puts off unpleasant tasks.
        /// </summary>
        public static string Trait_Orderliness_Low {
            get {
                return ResourceManager.GetString("Trait_Orderliness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderliness.
        /// </summary>
        public static string Trait_Orderliness_Name {
            get {
                return ResourceManager.GetString("Trait_Orderliness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how guarded one is with personal info.
        /// </summary>
        public static string Trait_Reserve_Description {
            get {
                return ResourceManager.GetString("Trait_Reserve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private, discreet, reserved, nondisclosing, hard to get to know, bottles up feelings, keeps thoughts to oneself.
        /// </summary>
        public static string Trait_Reserve_High {
            get {
                return ResourceManager.GetString("Trait_Reserve_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forthright, open, genuine, shares feelings and thoughts, easy to get to know, transparent, willing to talk about self.
        /// </summary>
        public static string Trait_Reserve_Low {
            get {
                return ResourceManager.GetString("Trait_Reserve_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Trait_Reserve_Name {
            get {
                return ResourceManager.GetString("Trait_Reserve_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how attuned one is to aesthetics/emotion.
        /// </summary>
        public static string Trait_Sensitivity_Description {
            get {
                return ResourceManager.GetString("Trait_Sensitivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tender-minded, sensitive, aesthetic, intuitive, enjoys art and fiction, emotionally responsive, moved by beauty.
        /// </summary>
        public static string Trait_Sensitivity_High {
            get {
                return ResourceManager.GetString("Trait_Sensitivity_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsentimental, objective, tough-minded, practical, not drawn to art or poetry, rarely notices emotional reactions.
        /// </summary>
        public static string Trait_Sensitivity_Low {
            get {
                return ResourceManager.GetString("Trait_Sensitivity_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        public static string Trait_Sensitivity_Name {
            get {
                return ResourceManager.GetString("Trait_Sensitivity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how socially confident one is.
        /// </summary>
        public static string Trait_SocialConfidence_Description {
            get {
                return ResourceManager.GetString("Trait_SocialConfidence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socially bold, outgoing, makes friends easily, comfortable with attention, starts conversations, at ease with people.
        /// </summary>
        public static string Trait_SocialConfidence_High {
            get {
                return ResourceManager.GetString("Trait_SocialConfidence_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shy, socially hesitant, quiet around strangers, keeps in the background, uncomfortable with attention, finds it hard to approach others.
        /// </summary>
        public static string Trait_SocialConfidence_Low {
            get {
                return ResourceManager.GetString("Trait_SocialConfidence_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Confidence.
        /// </summary>
        public static string Trait_SocialConfidence_Name {
            get {
                return ResourceManager.GetString("Trait_SocialConfidence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how empathetic one is to others.
        /// </summary>
        public static string Trait_Warmth_Description {
            get {
                return ResourceManager.GetString("Trait_Warmth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empathetic, comforting, interested in others, feels others&apos; emotions, brings people together, makes others feel at ease.
        /// </summary>
        public static string Trait_Warmth_High {
            get {
                return ResourceManager.GetString("Trait_Warmth_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved, emotionally distant, detached, disinterested in others&apos; problems, keeps to oneself.
        /// </summary>
        public static string Trait_Warmth_Low {
            get {
                return ResourceManager.GetString("Trait_Warmth_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmth.
        /// </summary>
        public static string Trait_Warmth_Name {
            get {
                return ResourceManager.GetString("Trait_Warmth_Name", resourceCulture);
            }
        }
    }
}
